apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: s4f9s1tp4-go 
  janus-idp.io/tekton: s4f9s1tp4-go
  backstage.io/kubernetes-id: s4f9s1tp4-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: s4f9s1tp4-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml